### PR TITLE
Es6 and code cleanup

### PR DESCRIPTION
**Pull request by kkota1**
Saw arrow notation used sporadically, so figured the node parts are meant to be es6 compatible anyway, so implemented it where applicable.

Spacing and semicolons

Also includes changes from closed https://github.com/naptha/tesseract.js/pull/39

Version 1.0.8

### CODE REVIEW

**Comment by bijection** [comment]
Can you update this to only include your changes to src?

**Comment by kkota1** [comment]
@bijection done

**Comment by djyde** [comment]
maybe you should not change the version on `package.json`

**Comment by kkota1** [comment]
removed changes to package.json

**Comment by bijection** [comment]
Thanks!

**Comment by yekiyeard** [comment]
)

   - f91f8c0 <https://github.com/naptha/tesseract.js/commit/f91f8c0> resolve
   conflict


2016-10-22 11:42 GMT-04:00 Guillermo Webster <notifications@github.com>:

**Pull request merged**
