### PR TITLE
Fix images' orientation based on exif data

### PR DESCRIPTION
**Pull request by rogerxaic**
Images taken with Apple products might have a problem with orientation. Indeed, Apple includes orientation information in the photo's EXIF data rather than rotating it, and expects visualization software to read and apply the EXIF data in order to correctly display the image.

In the case of Tesseract, the image is not rotated and thus recognized as is. This PR fixes this issue both on browser and node lib.

### CODE REVIEW

**Comment by jeromewu** [comment]
@rogerxaic Thanks a lot for your PR!
But sadly as the CI is not passing, can you kindly help to fix the lint issue to keep the code quality of this repo? Thanks.
CI Issues link: https://travis-ci.org/github/naptha/tesseract.js/builds/674757966

**Comment by tim-krieger** [comment]
@rogerxaic We use tesseract.js in a school project. Since many students have an iPad this pull request is very important for us. Maybe we can help here? You can also contact me via email. Thanks a lot!

**Comment by jeromewu** [comment]
@rogerxaic thanks for the PR again. Although there are still some CI issue, I managed to fix it.

@tim-krieger please check if v2.1.2 works for you. :smiley:

**Comment by tim-krieger** [comment]
@jeromewu Thank you! This is really cool. Sadly I'm a newbie. We have implementet tesseract.js in a [word cloud generator](https://github.com/nickyreinert/wordCloud-for-Wordpress). I've changed this line in initOCR.js

`https://unpkg.com/tesseract.js@v2.1.2/dist/worker.min.js`

With no success with my iPad. Textrecognition with the »right« orientation works well. Should I also change this file?

`https://unpkg.com/tesseract.js-core@v2.1.2/tesseract-core.wasm.js`

**Comment by jeromewu** [comment]
@tim-krieger 

I think you should update this file to the latest version: https://github.com/nickyreinert/wordCloud-for-Wordpress/blob/wordCloud-for-wordPress-2/lib/tesseract.min.js and use the latest worker.min.js.

In fact I don't have any images to test this orientation issue, would you mind sending me some example images so I can try to fix it?

**Pull request merged**
