### PR TITLE
Node fix: allowing a local langPath to be used when looking for language files

### PR DESCRIPTION
**Pull request by mikewesthad**
**BACKGROUND**
A few issues have opened up relating to using a local `langPath` in the node flavor of tesseract.js (relevant issues: #136 #130). There seems to be a problem with the cdn.rawgit headers served from the tessdata repo (see #136).

**PR**
When I attempted to use a local path for my `langPath`, I ran into errors because tesseract expects the local language file to be wherever the node process is started. It seems that the `langPath` option is only there to be used for specifying an alternate URL for downloading trained language files. This PR remedies that and allows a local `langPath` to be used. E.g. you could download English and Spanish trained data to a `langs/` folder.

**USAGE**
```js
const path = require("path");
const options = {
    langPath: path.join(__dirname, "langs") // Or wherever your downloaded langs are stored
};
Tesseract.recognize(image, {lang: "eng"}) // Or whichever lang you have downloaded to langs/
    .then((result) => console.log(result.text));
```

### CODE REVIEW

**Comment by rhyek** [comment]
Could this please be merged? I have tested it on my project and it is needed functionality. Thank you.

**Comment by FlanGrande** [comment]
We should totally merge this, or, for that matter, anything that allows us to use a local traineddata file.
As @rhyek said, this is **needed** functionality.

**Comment by albertytau** [comment]
Thanks @mikewesthad , i have download your FORKED project. But, I still have the same issue if I refer to the tesseract.js at the dist folder. Do I need to setup anything to source the lang.js file you have updated in the src/node folder.

Also for the traineddata, I have unzip the file and place in the langs folder. It can be read but i still have the same error

Failed loading language 'eng'
Tesseract couldn't load any languages!
screen shot 2017-08-15 at 10 10 12 pm

**Comment by mikewesthad** [comment]
@albertytau, ah it could be because I didn't create a new build of the js files. I just altered the source code, figuring the new build would happen if the PR is accepted. I just regenerated the build, so if you pull the latest version, it might fix the problem. Is there a reason you are using the dist/js inside of node (instead of just `require`ing the source files)?

**Comment by albertytau** [comment]
@mikewesthad HI Michael, many thanks for your prompt reply and fix.
I use the dist as it stands for final and distribution version. 
I have downloaded the new version and I still have challenge to load the local file.

Here is my code

    var tesspath = (function() { //absolute path
    var pathArray = window.location.pathname.split( '/' );
    pathArray.pop(); //Remove the last ("**.html")
    return window.location.origin + pathArray.join("/");
    })();    
    
    $scope.tesseract_defaultOptions = {
    workerPath: 'https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/worker.js',
    langPath: 'https://cdn.rawgit.com/naptha/tessdata/gh-pages/3.02/',
    corePath: 'https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js'     
    };
    
    $scope.tesseract_offlineOptions = {
    workerPath: tesspath + '/lib/tesseract.js-master/dist/worker.js',
    langPath: tesspath + '/lib/tesseract.js-master/langs/',
    corePath: tesspath + '/lib/tesseract.js-master/core/index.js',
    }; 

        window.Tesseract = Tesseract.create($scope.tesseract_offlineOptions);     
        
        Tesseract.recognize(imageData, {
            lang: "eng"
        }).progress(function  (p) {
            console.log('progress', p);
            $scope.ocr_percent = $scope.completeness(p.progress);
            $scope.ocr_result = p.status;
        })
        .then(function (result) {
            console.log('result', result);
            $scope.ocr_result = result.text;
            $scope.ocr_confidence = result.confidence;
            $scope.toLUIS();
        });

screen shot 2017-08-15 at 11 47 06 pm
screen shot 2017-08-15 at 11 46 39 pm

**Comment by mikewesthad** [comment]
@albertytau - ah you aren't using Node, you are using a browser. This specific PR is for fixing an issue with running tesseract.js in Node, not the browser. What you are running into is a separate problem, I'd look around the issues that have been posted to see if anyone is having similar problems. If not, you can always open up a new issue. Good luck

**Comment by albertytau** [comment]
@mikewesthad , many thanks for your superb help :)

**Comment by ForcedUnknown** [comment]
yes this helped with a pokemon go project I'm working on, so very much thank you mike! the team and I look forward to this getting merged in!

**Comment by aaronwbrown** [comment]
Would love to see this merged in as well.

**Comment by aaronwbrown** [comment]
@antimatter15 - Thanks for the merge! Should we expect a version bump on this?

**Pull request merged**
