### PR TITLE
BMP support.

### PR DESCRIPTION
**Pull request by hemanth**
`BMP` support.

### CODE REVIEW

**Comment by Devehab** [comment]
worker.js:11953 Uncaught DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': An object could not be cloned.(…)

**Comment by hemanth** [comment]
?

**Comment by jeromewu** [comment]
The new version of tesseract.js will support uncompressed bmp by default, so this PR is not needed now.

**Comment by hemanth** [comment]
👍

**Pull request closed without merging**
